name: flutter_ngine_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  cli_util: ^0.4.1
  io: ^1.0.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2

executables:
  ngine: