name: juno_getx_base_project
description: A boilerplate template of Flutter GetX for Neuorogine Mobile team.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: "3.16.9"

dependencies:
  animations: ^2.0.7
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^5.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.2
  fluttertoast: ^8.2.1
  font_awesome_flutter: ^10.4.0
  get: ^4.6.5
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  logger: ^1.2.2
  package_info_plus: ^3.0.3
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.18
  ua_client_hints: ^1.1.3

dev_dependencies:
  analyzer: 5.4.0
  build_runner: ^2.3.3
  change_app_package_name: ^1.1.0
  dart_code_metrics: 5.5.1
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env.uat
    - .env.development
    - .env.production

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Thin.ttf
          weight: 200
        - asset: fonts/Roboto-Light.ttf
          weight: 200
        - asset: fonts/Roboto-Regular.ttf
          weight: 200
        - asset: fonts/Roboto-Medium.ttf
          weight: 300
        - asset: fonts/Roboto-Bold.ttf
          weight: 600
        - asset: fonts/Roboto-Italic.ttf
          style: italic
